export const ROUTE_TITLES: Record<string, string> = {
  "/auth/login": "Login | Cropnest",
  "/home": "Home | Cropnest",
  "/dashboard": "Dashboard | Cropnest",
  "/dashboardp": "Promoter Dashboard | Cropnest",
  "/usersList": "User Management | Cropnest",
  "/userDetails": "User Details | Cropnest",
  "/bannerList": "Banner Management | Cropnest",
  "/cropList": "Crop Management | Cropnest",
  "/assetsList": "Asset Management | Cropnest",
  "/addressList": "Address Management | Cropnest",
  "/createBanner": "Create Banner | Cropnest",
  "/createCrop": "Create Crop | Cropnest",
  "/createAssets": "Create Asset | Cropnest",
  "/createAddress": "Create Address | Cropnest",
  "/editBanner": "Edit Banner | Cropnest",
  "/editCrop": "Edit Crop | Cropnest",
  "/editAssets": "Edit Asset | Cropnest",
  "/editUsers": "Edit User | Cropnest",
};
