/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as promoterRouteRouteImport } from './routes/(promoter)/route'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as promoterVerifyUserOtpRouteImport } from './routes/(promoter)/verifyUserOtp'
import { Route as promoterVerifyDrivingLicenceRouteImport } from './routes/(promoter)/verifyDrivingLicence'
import { Route as promoterVerificationVehicalRouteImport } from './routes/(promoter)/verificationVehical'
import { Route as promoterVehicleDetailsRouteImport } from './routes/(promoter)/vehicleDetails'
import { Route as promoterPromoterUserDetailsRouteImport } from './routes/(promoter)/promoterUserDetails'
import { Route as promoterMyProfileRouteImport } from './routes/(promoter)/myProfile'
import { Route as promoterMyPerformanceRouteImport } from './routes/(promoter)/myPerformance'
import { Route as promoterMyNetworkRouteImport } from './routes/(promoter)/myNetwork'
import { Route as promoterEditUserRouteImport } from './routes/(promoter)/editUser'
import { Route as promoterEditProfileRouteImport } from './routes/(promoter)/editProfile'
import { Route as promoterDrivingLicenceRouteImport } from './routes/(promoter)/drivingLicence'
import { Route as promoterDashboardpRouteImport } from './routes/(promoter)/dashboardp'
import { Route as promoterCreateTripRouteImport } from './routes/(promoter)/createTrip'
import { Route as promoterAddvehicalRouteImport } from './routes/(promoter)/addvehical'
import { Route as promoterAddUserRouteImport } from './routes/(promoter)/addUser'
import { Route as adminUsersListRouteImport } from './routes/(admin)/usersList'
import { Route as adminUserDetailsRouteImport } from './routes/(admin)/userDetails'
import { Route as adminPromoterListRouteImport } from './routes/(admin)/promoterList'
import { Route as adminPromoterFormRouteImport } from './routes/(admin)/promoterForm'
import { Route as adminPromoterEditRouteImport } from './routes/(admin)/promoterEdit'
import { Route as adminPromoterDetailsRouteImport } from './routes/(admin)/promoterDetails'
import { Route as adminDashboardRouteImport } from './routes/(admin)/dashboard'

const promoterRouteRoute = promoterRouteRouteImport.update({
  id: '/(promoter)',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const promoterVerifyUserOtpRoute = promoterVerifyUserOtpRouteImport.update({
  id: '/verifyUserOtp',
  path: '/verifyUserOtp',
  getParentRoute: () => promoterRouteRoute,
} as any)
const promoterVerifyDrivingLicenceRoute =
  promoterVerifyDrivingLicenceRouteImport.update({
    id: '/verifyDrivingLicence',
    path: '/verifyDrivingLicence',
    getParentRoute: () => promoterRouteRoute,
  } as any)
const promoterVerificationVehicalRoute =
  promoterVerificationVehicalRouteImport.update({
    id: '/verificationVehical',
    path: '/verificationVehical',
    getParentRoute: () => promoterRouteRoute,
  } as any)
const promoterVehicleDetailsRoute = promoterVehicleDetailsRouteImport.update({
  id: '/vehicleDetails',
  path: '/vehicleDetails',
  getParentRoute: () => promoterRouteRoute,
} as any)
const promoterPromoterUserDetailsRoute =
  promoterPromoterUserDetailsRouteImport.update({
    id: '/promoterUserDetails',
    path: '/promoterUserDetails',
    getParentRoute: () => promoterRouteRoute,
  } as any)
const promoterMyProfileRoute = promoterMyProfileRouteImport.update({
  id: '/myProfile',
  path: '/myProfile',
  getParentRoute: () => promoterRouteRoute,
} as any)
const promoterMyPerformanceRoute = promoterMyPerformanceRouteImport.update({
  id: '/myPerformance',
  path: '/myPerformance',
  getParentRoute: () => promoterRouteRoute,
} as any)
const promoterMyNetworkRoute = promoterMyNetworkRouteImport.update({
  id: '/myNetwork',
  path: '/myNetwork',
  getParentRoute: () => promoterRouteRoute,
} as any)
const promoterEditUserRoute = promoterEditUserRouteImport.update({
  id: '/editUser',
  path: '/editUser',
  getParentRoute: () => promoterRouteRoute,
} as any)
const promoterEditProfileRoute = promoterEditProfileRouteImport.update({
  id: '/editProfile',
  path: '/editProfile',
  getParentRoute: () => promoterRouteRoute,
} as any)
const promoterDrivingLicenceRoute = promoterDrivingLicenceRouteImport.update({
  id: '/drivingLicence',
  path: '/drivingLicence',
  getParentRoute: () => promoterRouteRoute,
} as any)
const promoterDashboardpRoute = promoterDashboardpRouteImport.update({
  id: '/dashboardp',
  path: '/dashboardp',
  getParentRoute: () => promoterRouteRoute,
} as any)
const promoterCreateTripRoute = promoterCreateTripRouteImport.update({
  id: '/createTrip',
  path: '/createTrip',
  getParentRoute: () => promoterRouteRoute,
} as any)
const promoterAddvehicalRoute = promoterAddvehicalRouteImport.update({
  id: '/addvehical',
  path: '/addvehical',
  getParentRoute: () => promoterRouteRoute,
} as any)
const promoterAddUserRoute = promoterAddUserRouteImport.update({
  id: '/addUser',
  path: '/addUser',
  getParentRoute: () => promoterRouteRoute,
} as any)
const adminUsersListRoute = adminUsersListRouteImport.update({
  id: '/usersList',
  path: '/usersList',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminUserDetailsRoute = adminUserDetailsRouteImport.update({
  id: '/userDetails',
  path: '/userDetails',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminPromoterListRoute = adminPromoterListRouteImport.update({
  id: '/promoterList',
  path: '/promoterList',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminPromoterFormRoute = adminPromoterFormRouteImport.update({
  id: '/promoterForm',
  path: '/promoterForm',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminPromoterEditRoute = adminPromoterEditRouteImport.update({
  id: '/promoterEdit',
  path: '/promoterEdit',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminPromoterDetailsRoute = adminPromoterDetailsRouteImport.update({
  id: '/promoterDetails',
  path: '/promoterDetails',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminDashboardRoute = adminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => adminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof adminDashboardRoute
  '/promoterDetails': typeof adminPromoterDetailsRoute
  '/promoterEdit': typeof adminPromoterEditRoute
  '/promoterForm': typeof adminPromoterFormRoute
  '/promoterList': typeof adminPromoterListRoute
  '/userDetails': typeof adminUserDetailsRoute
  '/usersList': typeof adminUsersListRoute
  '/addUser': typeof promoterAddUserRoute
  '/addvehical': typeof promoterAddvehicalRoute
  '/createTrip': typeof promoterCreateTripRoute
  '/dashboardp': typeof promoterDashboardpRoute
  '/drivingLicence': typeof promoterDrivingLicenceRoute
  '/editProfile': typeof promoterEditProfileRoute
  '/editUser': typeof promoterEditUserRoute
  '/myNetwork': typeof promoterMyNetworkRoute
  '/myPerformance': typeof promoterMyPerformanceRoute
  '/myProfile': typeof promoterMyProfileRoute
  '/promoterUserDetails': typeof promoterPromoterUserDetailsRoute
  '/vehicleDetails': typeof promoterVehicleDetailsRoute
  '/verificationVehical': typeof promoterVerificationVehicalRoute
  '/verifyDrivingLicence': typeof promoterVerifyDrivingLicenceRoute
  '/verifyUserOtp': typeof promoterVerifyUserOtpRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof adminDashboardRoute
  '/promoterDetails': typeof adminPromoterDetailsRoute
  '/promoterEdit': typeof adminPromoterEditRoute
  '/promoterForm': typeof adminPromoterFormRoute
  '/promoterList': typeof adminPromoterListRoute
  '/userDetails': typeof adminUserDetailsRoute
  '/usersList': typeof adminUsersListRoute
  '/addUser': typeof promoterAddUserRoute
  '/addvehical': typeof promoterAddvehicalRoute
  '/createTrip': typeof promoterCreateTripRoute
  '/dashboardp': typeof promoterDashboardpRoute
  '/drivingLicence': typeof promoterDrivingLicenceRoute
  '/editProfile': typeof promoterEditProfileRoute
  '/editUser': typeof promoterEditUserRoute
  '/myNetwork': typeof promoterMyNetworkRoute
  '/myPerformance': typeof promoterMyPerformanceRoute
  '/myProfile': typeof promoterMyProfileRoute
  '/promoterUserDetails': typeof promoterPromoterUserDetailsRoute
  '/vehicleDetails': typeof promoterVehicleDetailsRoute
  '/verificationVehical': typeof promoterVerificationVehicalRoute
  '/verifyDrivingLicence': typeof promoterVerifyDrivingLicenceRoute
  '/verifyUserOtp': typeof promoterVerifyUserOtpRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminRouteRouteWithChildren
  '/(promoter)': typeof promoterRouteRouteWithChildren
  '/(admin)/dashboard': typeof adminDashboardRoute
  '/(admin)/promoterDetails': typeof adminPromoterDetailsRoute
  '/(admin)/promoterEdit': typeof adminPromoterEditRoute
  '/(admin)/promoterForm': typeof adminPromoterFormRoute
  '/(admin)/promoterList': typeof adminPromoterListRoute
  '/(admin)/userDetails': typeof adminUserDetailsRoute
  '/(admin)/usersList': typeof adminUsersListRoute
  '/(promoter)/addUser': typeof promoterAddUserRoute
  '/(promoter)/addvehical': typeof promoterAddvehicalRoute
  '/(promoter)/createTrip': typeof promoterCreateTripRoute
  '/(promoter)/dashboardp': typeof promoterDashboardpRoute
  '/(promoter)/drivingLicence': typeof promoterDrivingLicenceRoute
  '/(promoter)/editProfile': typeof promoterEditProfileRoute
  '/(promoter)/editUser': typeof promoterEditUserRoute
  '/(promoter)/myNetwork': typeof promoterMyNetworkRoute
  '/(promoter)/myPerformance': typeof promoterMyPerformanceRoute
  '/(promoter)/myProfile': typeof promoterMyProfileRoute
  '/(promoter)/promoterUserDetails': typeof promoterPromoterUserDetailsRoute
  '/(promoter)/vehicleDetails': typeof promoterVehicleDetailsRoute
  '/(promoter)/verificationVehical': typeof promoterVerificationVehicalRoute
  '/(promoter)/verifyDrivingLicence': typeof promoterVerifyDrivingLicenceRoute
  '/(promoter)/verifyUserOtp': typeof promoterVerifyUserOtpRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/promoterDetails'
    | '/promoterEdit'
    | '/promoterForm'
    | '/promoterList'
    | '/userDetails'
    | '/usersList'
    | '/addUser'
    | '/addvehical'
    | '/createTrip'
    | '/dashboardp'
    | '/drivingLicence'
    | '/editProfile'
    | '/editUser'
    | '/myNetwork'
    | '/myPerformance'
    | '/myProfile'
    | '/promoterUserDetails'
    | '/vehicleDetails'
    | '/verificationVehical'
    | '/verifyDrivingLicence'
    | '/verifyUserOtp'
    | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/promoterDetails'
    | '/promoterEdit'
    | '/promoterForm'
    | '/promoterList'
    | '/userDetails'
    | '/usersList'
    | '/addUser'
    | '/addvehical'
    | '/createTrip'
    | '/dashboardp'
    | '/drivingLicence'
    | '/editProfile'
    | '/editUser'
    | '/myNetwork'
    | '/myPerformance'
    | '/myProfile'
    | '/promoterUserDetails'
    | '/vehicleDetails'
    | '/verificationVehical'
    | '/verifyDrivingLicence'
    | '/verifyUserOtp'
    | '/auth/login'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/(promoter)'
    | '/(admin)/dashboard'
    | '/(admin)/promoterDetails'
    | '/(admin)/promoterEdit'
    | '/(admin)/promoterForm'
    | '/(admin)/promoterList'
    | '/(admin)/userDetails'
    | '/(admin)/usersList'
    | '/(promoter)/addUser'
    | '/(promoter)/addvehical'
    | '/(promoter)/createTrip'
    | '/(promoter)/dashboardp'
    | '/(promoter)/drivingLicence'
    | '/(promoter)/editProfile'
    | '/(promoter)/editUser'
    | '/(promoter)/myNetwork'
    | '/(promoter)/myPerformance'
    | '/(promoter)/myProfile'
    | '/(promoter)/promoterUserDetails'
    | '/(promoter)/vehicleDetails'
    | '/(promoter)/verificationVehical'
    | '/(promoter)/verifyDrivingLicence'
    | '/(promoter)/verifyUserOtp'
    | '/auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminRouteRoute: typeof adminRouteRouteWithChildren
  promoterRouteRoute: typeof promoterRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(promoter)': {
      id: '/(promoter)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof promoterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(promoter)/verifyUserOtp': {
      id: '/(promoter)/verifyUserOtp'
      path: '/verifyUserOtp'
      fullPath: '/verifyUserOtp'
      preLoaderRoute: typeof promoterVerifyUserOtpRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/verifyDrivingLicence': {
      id: '/(promoter)/verifyDrivingLicence'
      path: '/verifyDrivingLicence'
      fullPath: '/verifyDrivingLicence'
      preLoaderRoute: typeof promoterVerifyDrivingLicenceRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/verificationVehical': {
      id: '/(promoter)/verificationVehical'
      path: '/verificationVehical'
      fullPath: '/verificationVehical'
      preLoaderRoute: typeof promoterVerificationVehicalRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/vehicleDetails': {
      id: '/(promoter)/vehicleDetails'
      path: '/vehicleDetails'
      fullPath: '/vehicleDetails'
      preLoaderRoute: typeof promoterVehicleDetailsRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/promoterUserDetails': {
      id: '/(promoter)/promoterUserDetails'
      path: '/promoterUserDetails'
      fullPath: '/promoterUserDetails'
      preLoaderRoute: typeof promoterPromoterUserDetailsRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/myProfile': {
      id: '/(promoter)/myProfile'
      path: '/myProfile'
      fullPath: '/myProfile'
      preLoaderRoute: typeof promoterMyProfileRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/myPerformance': {
      id: '/(promoter)/myPerformance'
      path: '/myPerformance'
      fullPath: '/myPerformance'
      preLoaderRoute: typeof promoterMyPerformanceRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/myNetwork': {
      id: '/(promoter)/myNetwork'
      path: '/myNetwork'
      fullPath: '/myNetwork'
      preLoaderRoute: typeof promoterMyNetworkRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/editUser': {
      id: '/(promoter)/editUser'
      path: '/editUser'
      fullPath: '/editUser'
      preLoaderRoute: typeof promoterEditUserRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/editProfile': {
      id: '/(promoter)/editProfile'
      path: '/editProfile'
      fullPath: '/editProfile'
      preLoaderRoute: typeof promoterEditProfileRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/drivingLicence': {
      id: '/(promoter)/drivingLicence'
      path: '/drivingLicence'
      fullPath: '/drivingLicence'
      preLoaderRoute: typeof promoterDrivingLicenceRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/dashboardp': {
      id: '/(promoter)/dashboardp'
      path: '/dashboardp'
      fullPath: '/dashboardp'
      preLoaderRoute: typeof promoterDashboardpRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/createTrip': {
      id: '/(promoter)/createTrip'
      path: '/createTrip'
      fullPath: '/createTrip'
      preLoaderRoute: typeof promoterCreateTripRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/addvehical': {
      id: '/(promoter)/addvehical'
      path: '/addvehical'
      fullPath: '/addvehical'
      preLoaderRoute: typeof promoterAddvehicalRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(promoter)/addUser': {
      id: '/(promoter)/addUser'
      path: '/addUser'
      fullPath: '/addUser'
      preLoaderRoute: typeof promoterAddUserRouteImport
      parentRoute: typeof promoterRouteRoute
    }
    '/(admin)/usersList': {
      id: '/(admin)/usersList'
      path: '/usersList'
      fullPath: '/usersList'
      preLoaderRoute: typeof adminUsersListRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/userDetails': {
      id: '/(admin)/userDetails'
      path: '/userDetails'
      fullPath: '/userDetails'
      preLoaderRoute: typeof adminUserDetailsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/promoterList': {
      id: '/(admin)/promoterList'
      path: '/promoterList'
      fullPath: '/promoterList'
      preLoaderRoute: typeof adminPromoterListRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/promoterForm': {
      id: '/(admin)/promoterForm'
      path: '/promoterForm'
      fullPath: '/promoterForm'
      preLoaderRoute: typeof adminPromoterFormRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/promoterEdit': {
      id: '/(admin)/promoterEdit'
      path: '/promoterEdit'
      fullPath: '/promoterEdit'
      preLoaderRoute: typeof adminPromoterEditRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/promoterDetails': {
      id: '/(admin)/promoterDetails'
      path: '/promoterDetails'
      fullPath: '/promoterDetails'
      preLoaderRoute: typeof adminPromoterDetailsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/dashboard': {
      id: '/(admin)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof adminDashboardRouteImport
      parentRoute: typeof adminRouteRoute
    }
  }
}

interface adminRouteRouteChildren {
  adminDashboardRoute: typeof adminDashboardRoute
  adminPromoterDetailsRoute: typeof adminPromoterDetailsRoute
  adminPromoterEditRoute: typeof adminPromoterEditRoute
  adminPromoterFormRoute: typeof adminPromoterFormRoute
  adminPromoterListRoute: typeof adminPromoterListRoute
  adminUserDetailsRoute: typeof adminUserDetailsRoute
  adminUsersListRoute: typeof adminUsersListRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminDashboardRoute: adminDashboardRoute,
  adminPromoterDetailsRoute: adminPromoterDetailsRoute,
  adminPromoterEditRoute: adminPromoterEditRoute,
  adminPromoterFormRoute: adminPromoterFormRoute,
  adminPromoterListRoute: adminPromoterListRoute,
  adminUserDetailsRoute: adminUserDetailsRoute,
  adminUsersListRoute: adminUsersListRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

interface promoterRouteRouteChildren {
  promoterAddUserRoute: typeof promoterAddUserRoute
  promoterAddvehicalRoute: typeof promoterAddvehicalRoute
  promoterCreateTripRoute: typeof promoterCreateTripRoute
  promoterDashboardpRoute: typeof promoterDashboardpRoute
  promoterDrivingLicenceRoute: typeof promoterDrivingLicenceRoute
  promoterEditProfileRoute: typeof promoterEditProfileRoute
  promoterEditUserRoute: typeof promoterEditUserRoute
  promoterMyNetworkRoute: typeof promoterMyNetworkRoute
  promoterMyPerformanceRoute: typeof promoterMyPerformanceRoute
  promoterMyProfileRoute: typeof promoterMyProfileRoute
  promoterPromoterUserDetailsRoute: typeof promoterPromoterUserDetailsRoute
  promoterVehicleDetailsRoute: typeof promoterVehicleDetailsRoute
  promoterVerificationVehicalRoute: typeof promoterVerificationVehicalRoute
  promoterVerifyDrivingLicenceRoute: typeof promoterVerifyDrivingLicenceRoute
  promoterVerifyUserOtpRoute: typeof promoterVerifyUserOtpRoute
}

const promoterRouteRouteChildren: promoterRouteRouteChildren = {
  promoterAddUserRoute: promoterAddUserRoute,
  promoterAddvehicalRoute: promoterAddvehicalRoute,
  promoterCreateTripRoute: promoterCreateTripRoute,
  promoterDashboardpRoute: promoterDashboardpRoute,
  promoterDrivingLicenceRoute: promoterDrivingLicenceRoute,
  promoterEditProfileRoute: promoterEditProfileRoute,
  promoterEditUserRoute: promoterEditUserRoute,
  promoterMyNetworkRoute: promoterMyNetworkRoute,
  promoterMyPerformanceRoute: promoterMyPerformanceRoute,
  promoterMyProfileRoute: promoterMyProfileRoute,
  promoterPromoterUserDetailsRoute: promoterPromoterUserDetailsRoute,
  promoterVehicleDetailsRoute: promoterVehicleDetailsRoute,
  promoterVerificationVehicalRoute: promoterVerificationVehicalRoute,
  promoterVerifyDrivingLicenceRoute: promoterVerifyDrivingLicenceRoute,
  promoterVerifyUserOtpRoute: promoterVerifyUserOtpRoute,
}

const promoterRouteRouteWithChildren = promoterRouteRoute._addFileChildren(
  promoterRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminRouteRoute: adminRouteRouteWithChildren,
  promoterRouteRoute: promoterRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
